# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f5df2a67e51efdf689ce07a815e0fe7143854069651ba1f9f74af4381ba96f66e5b94ad0282cc89eb06a88f1bee026f580e2f706ea67d07834a8d7b65e7fd84

test:
  secret_key_base: 41af02622bee26bf9ed1331697086c61e9e270f4b45848550ed489704f6bcebffd55de54d863d04894f29a22b67823a35fb7b5a31d9e11f0e0a4cb7d9687ff2b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
